name: ClusterFuzzLite batch fuzzing
on:
  workflow_dispatch:
  push:
    branches:
      - main  # Use your actual default branch here.
  schedule:
    - cron: '0 3 * * *'
permissions:
  contents: read
  actions: read
  security-events: write
jobs:
  BatchFuzzing:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sanitizer: [address, undefined]  # Override this with the sanitizers you want.
    steps:
    - name: Setup C++ tools
      uses: aminya/setup-cpp@v1.8.0
      with:
        ccache: true
    - name: Build Fuzzers (${{ matrix.sanitizer }})
      id: build
      uses: google/clusterfuzzlite/actions/build_fuzzers@v1
      with:
        sanitizer: ${{ matrix.sanitizer }}
    - name: Run Fuzzers (${{ matrix.sanitizer }}) with storage repo
      if: ${{ secrets.PERSONAL_ACCESS_TOKEN != '' }}
      id: run
      uses: google/clusterfuzzlite/actions/run_fuzzers@v1
      with:
        github-token: ${{ github.token }}
        fuzz-seconds: 600
        mode: 'batch'
        sanitizer: ${{ matrix.sanitizer }}
        storage-repo: https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/huangminghuang/hpp-proto-storage.git
        storage-repo-branch: main   # Optional. Defaults to "main"
        storage-repo-branch-coverage: gh-pages  # Optional. Defaults to "gh-pages".
    - name: Run Fuzzers (${{ matrix.sanitizer }}) without storage repo
      if: ${{ secrets.PERSONAL_ACCESS_TOKEN == '' }}
      id: run-no-storage
      uses: google/clusterfuzzlite/actions/run_fuzzers@v1
      with:
        github-token: ${{ github.token }}
        fuzz-seconds: 600
        mode: 'batch'
        sanitizer: ${{ matrix.sanitizer }}
